name: Build yoctobuilder

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
	permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build and push the image
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/prashantdivate/yoctobuilder:latest
          docker push ghcr.io/prashantdivate/yoctobuilder:latest
